# Generated by Django 5.2.6 on 2025-10-17 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='descripcion',
            new_name='hecho',
        ),
    ]
