# Generated by Django 5.2.6 on 2025-10-17 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_descripcion_tarea_hecho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='completada',
        ),
        migrations.AddField(
            model_name='tarea',
            name='descripcion',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tarea',
            name='hecho',
            field=models.BooleanField(default=False),
        ),
    ]
