# Generated by Django 5.2.6 on 2025-10-17 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_tarea_completada_tarea_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='usuario',
        ),
    ]
