# Generated by Django 5.2.6 on 2025-10-17 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_tarea_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='tarea',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
    ]
